name: Dev → Staging CI/CD

on:
  push:
    branches: [dev]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest tests/Unit --maxfail=1 --disable-warnings -q

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for merge conflicts with staging
        run: |
          git fetch origin staging
          git checkout staging
          if ! git merge --no-commit --no-ff dev; then
            echo "❌ Merge conflict detected. Manual resolution required."
            exit 1
          fi
          git reset --hard HEAD  # undo the test merge

      - name: Create or Update Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: staging
          branch: dev
          title: "Automated PR: dev → staging"
          body: "This PR is automatically created after passing unit tests."
          create-branch: false
          merge-method: merge  # auto merge PR if possible
          auto-merge: true     # enable automatic merge




