"""
name: Dev → Staging PR

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write


jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run Unit Tests
      - name: Run Unit Tests
        run: pytest tests/Unit --maxfail=1 --disable-warnings -q

      # 5. Create Pull Request to staging
      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.6
        with:
          github_token: ${{ secrets.PAT_TOKEN }}   # Your PAT secret
          source_branch: dev
          target_branch: staging
          title: "Automated PR: dev → staging"
          body: "This PR is automatically created after passing unit tests on the dev branch."
          label: automated
          draft: false
          get_diff: true
"""














