name: Dev → Staging PR

on:
  push:
    branches:
      - dev

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run Unit Tests
      - name: Run Unit Tests
        run: pytest tests/Unit --maxfail=1 --disable-warnings -q

      # 5. Create PR to staging if tests pass
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use a PAT with repo scope
          commit-message: "Auto-create PR from dev"
          title: "Automated PR: dev → staging"
          body: "This PR is automatically created after passing unit tests."
          head: dev
          base: staging
          labels: automated
          draft: false
          create-branch: false  # Use existing dev branch








