name: Dev → Staging PR

on:
  push:
    branches:
      - dev

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run Unit Tests
      - name: Run Unit Tests
        run: pytest tests/Unit --maxfail=1 --disable-warnings -q

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"    

      # 5. Create PR to staging if tests pass
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}       # PAT with repo scope
          commit-message: "Auto-create PR from dev"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: dev                             # Source branch (existing dev branch)
          base: staging                           # Target branch
          delete-branch: false                    # Keep dev branch
          title: "Automated PR: dev → staging"
          body: |
            This PR is automatically created after passing unit tests on the `dev` branch.
          labels: automated
          draft: false










